# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-aneesh"
BBFILE_PATTERN_meta-aneesh = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-aneesh = "6"

LAYERDEPENDS_meta-aneesh = "core"
LAYERSERIES_COMPAT_meta-aneesh = "kirkstone"
